#!/usr/bin/env bash
# Install the nutshell-server auto-updater. Lays down the live updater
# script + config at ~/.nutshell/, registers a 1-minute schedule with the
# platform's native scheduler (launchd / systemd-user / cron), and kicks
# off the first cycle so the server starts immediately.
#
# Usage:
#   bash scripts/install-updater.sh                      # bare server, no LLM
#   bash scripts/install-updater.sh --ollama             # match the start-with-llm.sh defaults
#   bash scripts/install-updater.sh --with-stt           # also install faster-whisper for server-side STT
#   bash scripts/install-updater.sh --ollama --with-stt  # both
#   bash scripts/install-updater.sh --ollama --port 4242 # extra args pass through
#   bash scripts/install-updater.sh --reinstall …        # nuke and re-install
#
# Args after the leading flags pass through to start-with-llm.sh on every
# server (re)launch. Edit them later by re-running with --reinstall, or
# by editing ~/.nutshell/config.sh directly.
#
# --with-stt installs faster-whisper + numpy via pip --user (with the
# --break-system-packages escape for Debian 12+ PEP 668 enforcement).
# The first /transcribe/stream call downloads the chosen Whisper
# model (~140MB for `base`) into ~/.cache/huggingface/. Adds ~5min
# to first install on a typical link.
#
# Idempotent: if ~/.nutshell/ already exists, prints a hint and exits 0.
# Pass --reinstall to overwrite.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
NUTSHELL_HOME="${NUTSHELL_HOME:-$HOME/.nutshell}"

PLIST_PATH="$HOME/Library/LaunchAgents/com.nutshell.updater.plist"
SYSTEMD_DIR="$HOME/.config/systemd/user"
SYSTEMD_SERVICE="$SYSTEMD_DIR/nutshell-updater.service"
SYSTEMD_TIMER="$SYSTEMD_DIR/nutshell-updater.timer"
CRON_MARKER='# nutshell-updater'

REINSTALL=0
WITH_STT=0
LAUNCH_ARGS=()
for arg in "$@"; do
  case "$arg" in
    --reinstall)
      REINSTALL=1
      ;;
    --with-stt)
      WITH_STT=1
      ;;
    *)
      LAUNCH_ARGS+=("$arg")
      ;;
  esac
done

say() { printf '\033[36m[install-updater]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[install-updater]\033[0m %s\n' "$*" >&2; }
die() { printf '\033[31m[install-updater]\033[0m %s\n' "$*" >&2; exit 1; }

# ── Pre-flight checks ───────────────────────────────────────────────────────

[ -d "${REPO_DIR}/.git" ] || die "${REPO_DIR} is not a git checkout — auto-update needs git fetch."
[ -x "${SCRIPT_DIR}/start-with-llm.sh" ] || die "${SCRIPT_DIR}/start-with-llm.sh missing or not executable."
[ -f "${SCRIPT_DIR}/_updater.sh" ] || die "${SCRIPT_DIR}/_updater.sh missing — repo is incomplete."

if [ -d "$NUTSHELL_HOME" ] && [ "$REINSTALL" -eq 0 ]; then
  cat <<EOF
Already installed at ${NUTSHELL_HOME}.

To update launch args:    bash scripts/install-updater.sh --reinstall ${LAUNCH_ARGS[*]:-}
To uninstall:             bash scripts/uninstall-updater.sh
To watch live:            tail -f ${NUTSHELL_HOME}/updater.log
EOF
  exit 0
fi

# Reinstall path: tear down the old schedule first so we don't end up with
# duplicates from cron or two launchd jobs racing.
if [ -d "$NUTSHELL_HOME" ] && [ "$REINSTALL" -eq 1 ]; then
  say "Reinstalling — clearing previous install"
  bash "${SCRIPT_DIR}/uninstall-updater.sh" --quiet || warn "uninstall step had warnings"
fi

# ── Lay down ~/.nutshell/ ───────────────────────────────────────────────────

say "Creating $NUTSHELL_HOME"
mkdir -p "$NUTSHELL_HOME"

# Build the LAUNCH_ARGS array literal for config.sh. Each arg is wrapped
# in single quotes; embedded single quotes are escaped via '\''.
quote_for_bash() {
  local s="$1"
  printf "'%s'" "${s//\'/\'\\\'\'}"
}

config_args=""
for a in "${LAUNCH_ARGS[@]:-}"; do
  config_args+=" $(quote_for_bash "$a")"
done

cat >"$NUTSHELL_HOME/config.sh" <<EOF
# Auto-generated by install-updater.sh. The next updater cycle picks up
# changes here, so you can edit launch args without --reinstall.
REPO_DIR="${REPO_DIR}"
LAUNCH_ARGS=(${config_args# })
EOF
chmod 600 "$NUTSHELL_HOME/config.sh"

say "Copying updater script to $NUTSHELL_HOME/updater.sh"
cp "${SCRIPT_DIR}/_updater.sh" "$NUTSHELL_HOME/updater.sh"
chmod +x "$NUTSHELL_HOME/updater.sh"

# Touch the log files so the first tail -f doesn't error out.
: >>"$NUTSHELL_HOME/updater.log"
: >>"$NUTSHELL_HOME/server.log"

# ── Register a schedule ─────────────────────────────────────────────────────

install_launchd() {
  say "Registering launchd job (every 60 s)"
  mkdir -p "$(dirname "$PLIST_PATH")"
  cat >"$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.nutshell.updater</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${NUTSHELL_HOME}/updater.sh</string>
    </array>
    <key>StartInterval</key>
    <integer>60</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${NUTSHELL_HOME}/launchd.log</string>
    <key>StandardErrorPath</key>
    <string>${NUTSHELL_HOME}/launchd.log</string>
</dict>
</plist>
EOF
  # `unload || true` in case a stale one is loaded under the same Label.
  launchctl unload -w "$PLIST_PATH" 2>/dev/null || true
  launchctl load -w "$PLIST_PATH"
}

install_systemd() {
  say "Registering systemd user timer (every 60 s)"
  mkdir -p "$SYSTEMD_DIR"
  # KillMode=process is essential: with the default control-group, systemd
  # cleans up the entire cgroup when this oneshot's ExecStart returns —
  # including the nohup-detached server we just spawned. KillMode=process
  # restricts cleanup to the updater bash itself, leaving the server alive.
  cat >"$SYSTEMD_SERVICE" <<EOF
[Unit]
Description=Nutshell server auto-updater (one cycle)

[Service]
Type=oneshot
KillMode=process
ExecStart=/bin/bash %h/.nutshell/updater.sh
StandardOutput=append:%h/.nutshell/systemd.log
StandardError=append:%h/.nutshell/systemd.log
EOF
  cat >"$SYSTEMD_TIMER" <<EOF
[Unit]
Description=Run nutshell-updater every minute

[Timer]
OnBootSec=10s
OnUnitActiveSec=1min
AccuracySec=10s
Unit=nutshell-updater.service

[Install]
WantedBy=timers.target
EOF
  systemctl --user daemon-reload
  systemctl --user enable --now nutshell-updater.timer
}

install_cron() {
  say "Registering cron entry (every minute) — no systemd available"
  local existing
  existing="$(crontab -l 2>/dev/null || true)"
  # Drop any prior lines we own, then append a fresh one.
  local cleaned
  cleaned="$(printf '%s\n' "$existing" | grep -v "$CRON_MARKER" || true)"
  {
    [ -n "$cleaned" ] && printf '%s\n' "$cleaned"
    printf '* * * * * /bin/bash %s/updater.sh >> %s/cron.log 2>&1 %s\n' \
      "$NUTSHELL_HOME" "$NUTSHELL_HOME" "$CRON_MARKER"
  } | crontab -
}

case "$(uname -s)" in
  Darwin)
    install_launchd
    ;;
  Linux)
    if systemctl --user list-units >/dev/null 2>&1; then
      install_systemd
    elif command -v crontab >/dev/null 2>&1; then
      install_cron
    else
      die "No supported scheduler found (need systemd-user or cron)."
    fi
    ;;
  *)
    die "Unsupported OS: $(uname -s). macOS and Linux only."
    ;;
esac

# ── Optional: faster-whisper for server-side STT ────────────────────────────

ensure_python3() {
  if command -v python3 >/dev/null 2>&1; then return 0; fi
  if command -v apt-get >/dev/null 2>&1 && [ "$EUID" -ne 0 ]; then
    say "python3 not found — installing via sudo apt"
    sudo apt-get install -y python3 || return 1
    return 0
  fi
  warn "python3 not found and no auto-install path. Install python3 manually then re-run with --with-stt."
  return 1
}

ensure_pip() {
  # Already there?
  if command -v pip3 >/dev/null 2>&1 || command -v pip >/dev/null 2>&1; then
    return 0
  fi
  # Auto-install python3-pip on Debian / Ubuntu — common case for the
  # target audience and the only platform where we know the package
  # name with confidence. Other distros: warn + skip.
  if command -v apt-get >/dev/null 2>&1 && [ "$EUID" -ne 0 ]; then
    say "pip not found — installing python3-pip via sudo apt"
    sudo apt-get install -y python3-pip || return 1
    return 0
  fi
  warn "pip / pip3 not found and no auto-install path. Install python3-pip manually then re-run with --with-stt."
  return 1
}

install_faster_whisper() {
  ensure_python3 || return 1
  ensure_pip || return 1

  local pip_cmd
  pip_cmd="$(command -v pip3 2>/dev/null || command -v pip 2>/dev/null || true)"
  if [ -z "$pip_cmd" ]; then
    warn "pip still not on PATH after install attempt — try a fresh shell."
    return 1
  fi

  if python3 -c "import faster_whisper" 2>/dev/null; then
    say "faster-whisper already installed — skipping pip install"
    return 0
  fi

  say "Installing faster-whisper + numpy via $pip_cmd"
  # Try plain --user first. PEP 668 (Debian 12+, Ubuntu 23.04+) blocks
  # system-wide pip; --break-system-packages is the documented escape
  # for "I really do want this in my user site-packages." Fall back
  # to it on the first failure rather than asking the user to retry.
  if ! "$pip_cmd" install --user faster-whisper numpy 2>/dev/null; then
    say "Plain --user install hit PEP 668 — retrying with --break-system-packages"
    if ! "$pip_cmd" install --user --break-system-packages faster-whisper numpy; then
      warn "pip install failed. Install manually: $pip_cmd install --user --break-system-packages faster-whisper numpy"
      return 1
    fi
  fi

  if python3 -c "import faster_whisper; print('OK', faster_whisper.__version__)" 2>&1 | grep -q '^OK'; then
    say "faster-whisper installed and imports cleanly"
    return 0
  fi
  warn "Install completed but import test failed — STT will not be available until faster-whisper imports cleanly from the systemd-user environment."
  warn "If python3 is on a venv path, set NUTSHELL_PYTHON_PATH in ~/.nutshell/config.sh."
  return 1
}

# Force the running server (if any) to exit so the next updater cycle
# respawns it with the fresh config.sh + freshly-probed feature flags.
# Without this, a reinstall that flipped features.transcribe doesn't
# light up until the user manually kills the server. Best-effort —
# we don't fail the install if no server was running.
force_server_restart() {
  local pid
  pid="$(pgrep -f "node.*nutshell-server.*cli\.js" 2>/dev/null | head -1 || true)"
  if [ -z "$pid" ]; then
    return 0
  fi
  say "Killing running server (pid=$pid) so the next updater cycle re-probes"
  kill -9 "$pid" 2>/dev/null || true
  sleep 1
}

if [ "$WITH_STT" -eq 1 ]; then
  install_faster_whisper || warn "STT install did not complete — server will start with features.transcribe=false. Re-run with --with-stt after fixing the issue."
fi

# Always force-restart the running server (if any) — the feature
# probes (claudeCode, transcribe) are cached at module load, so a
# reinstall that changed install state needs a fresh server process
# for /health to reflect reality.
force_server_restart

# ── First-cycle smoke test ──────────────────────────────────────────────────

say "Running first updater cycle"
if ! /bin/bash "$NUTSHELL_HOME/updater.sh"; then
  warn "First cycle returned non-zero. Check $NUTSHELL_HOME/updater.log"
fi

stt_status="not requested (re-run with --with-stt to enable)"
if [ "$WITH_STT" -eq 1 ]; then
  if python3 -c "import faster_whisper" 2>/dev/null; then
    stt_status="ready (faster-whisper installed)"
  else
    stt_status="install failed — see warnings above"
  fi
fi

cat <<EOF

Installed.

Server launch args:    ${LAUNCH_ARGS[*]:-(none)}
Repo:                  $REPO_DIR
State directory:       $NUTSHELL_HOME
STT (faster-whisper):  $stt_status

Useful commands:
  tail -f $NUTSHELL_HOME/updater.log         # updater activity
  tail -f $NUTSHELL_HOME/server.log          # server stdout/stderr
  bash scripts/install-updater.sh --reinstall          # change launch args
  bash scripts/install-updater.sh --reinstall --with-stt   # add STT to an existing install
  bash scripts/uninstall-updater.sh                    # remove everything

EOF
