#!/usr/bin/env bash
# Install the nutshell-server auto-updater. Lays down the live updater
# script + config at ~/.nutshell/, registers a 1-minute schedule with the
# platform's native scheduler (launchd / systemd-user / cron), and kicks
# off the first cycle so the server starts immediately.
#
# Usage:
#   bash scripts/install-updater.sh                      # bare server, no LLM
#   bash scripts/install-updater.sh --ollama             # match the start-with-llm.sh defaults
#   bash scripts/install-updater.sh --ollama --port 4242 # extra args pass through
#   bash scripts/install-updater.sh --reinstall …        # nuke and re-install
#
# Args after the leading flags pass through to start-with-llm.sh on every
# server (re)launch. Edit them later by re-running with --reinstall, or
# by editing ~/.nutshell/config.sh directly.
#
# Idempotent: if ~/.nutshell/ already exists, prints a hint and exits 0.
# Pass --reinstall to overwrite.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
NUTSHELL_HOME="${NUTSHELL_HOME:-$HOME/.nutshell}"

PLIST_PATH="$HOME/Library/LaunchAgents/com.nutshell.updater.plist"
SYSTEMD_DIR="$HOME/.config/systemd/user"
SYSTEMD_SERVICE="$SYSTEMD_DIR/nutshell-updater.service"
SYSTEMD_TIMER="$SYSTEMD_DIR/nutshell-updater.timer"
CRON_MARKER='# nutshell-updater'

REINSTALL=0
LAUNCH_ARGS=()
for arg in "$@"; do
  if [ "$arg" = "--reinstall" ]; then
    REINSTALL=1
  else
    LAUNCH_ARGS+=("$arg")
  fi
done

say() { printf '\033[36m[install-updater]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[install-updater]\033[0m %s\n' "$*" >&2; }
die() { printf '\033[31m[install-updater]\033[0m %s\n' "$*" >&2; exit 1; }

# ── Pre-flight checks ───────────────────────────────────────────────────────

[ -d "${REPO_DIR}/.git" ] || die "${REPO_DIR} is not a git checkout — auto-update needs git fetch."
[ -x "${SCRIPT_DIR}/start-with-llm.sh" ] || die "${SCRIPT_DIR}/start-with-llm.sh missing or not executable."
[ -f "${SCRIPT_DIR}/_updater.sh" ] || die "${SCRIPT_DIR}/_updater.sh missing — repo is incomplete."

if [ -d "$NUTSHELL_HOME" ] && [ "$REINSTALL" -eq 0 ]; then
  cat <<EOF
Already installed at ${NUTSHELL_HOME}.

To update launch args:    bash scripts/install-updater.sh --reinstall ${LAUNCH_ARGS[*]:-}
To uninstall:             bash scripts/uninstall-updater.sh
To watch live:            tail -f ${NUTSHELL_HOME}/updater.log
EOF
  exit 0
fi

# Reinstall path: tear down the old schedule first so we don't end up with
# duplicates from cron or two launchd jobs racing.
if [ -d "$NUTSHELL_HOME" ] && [ "$REINSTALL" -eq 1 ]; then
  say "Reinstalling — clearing previous install"
  bash "${SCRIPT_DIR}/uninstall-updater.sh" --quiet || warn "uninstall step had warnings"
fi

# ── Lay down ~/.nutshell/ ───────────────────────────────────────────────────

say "Creating $NUTSHELL_HOME"
mkdir -p "$NUTSHELL_HOME"

# Build the LAUNCH_ARGS array literal for config.sh. Each arg is wrapped
# in single quotes; embedded single quotes are escaped via '\''.
quote_for_bash() {
  local s="$1"
  printf "'%s'" "${s//\'/\'\\\'\'}"
}

config_args=""
for a in "${LAUNCH_ARGS[@]:-}"; do
  config_args+=" $(quote_for_bash "$a")"
done

cat >"$NUTSHELL_HOME/config.sh" <<EOF
# Auto-generated by install-updater.sh. The next updater cycle picks up
# changes here, so you can edit launch args without --reinstall.
REPO_DIR="${REPO_DIR}"
LAUNCH_ARGS=(${config_args# })
EOF
chmod 600 "$NUTSHELL_HOME/config.sh"

say "Copying updater script to $NUTSHELL_HOME/updater.sh"
cp "${SCRIPT_DIR}/_updater.sh" "$NUTSHELL_HOME/updater.sh"
chmod +x "$NUTSHELL_HOME/updater.sh"

# Touch the log files so the first tail -f doesn't error out.
: >>"$NUTSHELL_HOME/updater.log"
: >>"$NUTSHELL_HOME/server.log"

# ── Register a schedule ─────────────────────────────────────────────────────

install_launchd() {
  say "Registering launchd job (every 60 s)"
  mkdir -p "$(dirname "$PLIST_PATH")"
  cat >"$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.nutshell.updater</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${NUTSHELL_HOME}/updater.sh</string>
    </array>
    <key>StartInterval</key>
    <integer>60</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${NUTSHELL_HOME}/launchd.log</string>
    <key>StandardErrorPath</key>
    <string>${NUTSHELL_HOME}/launchd.log</string>
</dict>
</plist>
EOF
  # `unload || true` in case a stale one is loaded under the same Label.
  launchctl unload -w "$PLIST_PATH" 2>/dev/null || true
  launchctl load -w "$PLIST_PATH"
}

install_systemd() {
  say "Registering systemd user timer (every 60 s)"
  mkdir -p "$SYSTEMD_DIR"
  # KillMode=process is essential: with the default control-group, systemd
  # cleans up the entire cgroup when this oneshot's ExecStart returns —
  # including the nohup-detached server we just spawned. KillMode=process
  # restricts cleanup to the updater bash itself, leaving the server alive.
  cat >"$SYSTEMD_SERVICE" <<EOF
[Unit]
Description=Nutshell server auto-updater (one cycle)

[Service]
Type=oneshot
KillMode=process
ExecStart=/bin/bash %h/.nutshell/updater.sh
StandardOutput=append:%h/.nutshell/systemd.log
StandardError=append:%h/.nutshell/systemd.log
EOF
  cat >"$SYSTEMD_TIMER" <<EOF
[Unit]
Description=Run nutshell-updater every minute

[Timer]
OnBootSec=10s
OnUnitActiveSec=1min
AccuracySec=10s
Unit=nutshell-updater.service

[Install]
WantedBy=timers.target
EOF
  systemctl --user daemon-reload
  systemctl --user enable --now nutshell-updater.timer
}

install_cron() {
  say "Registering cron entry (every minute) — no systemd available"
  local existing
  existing="$(crontab -l 2>/dev/null || true)"
  # Drop any prior lines we own, then append a fresh one.
  local cleaned
  cleaned="$(printf '%s\n' "$existing" | grep -v "$CRON_MARKER" || true)"
  {
    [ -n "$cleaned" ] && printf '%s\n' "$cleaned"
    printf '* * * * * /bin/bash %s/updater.sh >> %s/cron.log 2>&1 %s\n' \
      "$NUTSHELL_HOME" "$NUTSHELL_HOME" "$CRON_MARKER"
  } | crontab -
}

case "$(uname -s)" in
  Darwin)
    install_launchd
    ;;
  Linux)
    if systemctl --user list-units >/dev/null 2>&1; then
      install_systemd
    elif command -v crontab >/dev/null 2>&1; then
      install_cron
    else
      die "No supported scheduler found (need systemd-user or cron)."
    fi
    ;;
  *)
    die "Unsupported OS: $(uname -s). macOS and Linux only."
    ;;
esac

# ── First-cycle smoke test ──────────────────────────────────────────────────

say "Running first updater cycle"
if ! /bin/bash "$NUTSHELL_HOME/updater.sh"; then
  warn "First cycle returned non-zero. Check $NUTSHELL_HOME/updater.log"
fi

cat <<EOF

Installed.

Server launch args:    ${LAUNCH_ARGS[*]:-(none)}
Repo:                  $REPO_DIR
State directory:       $NUTSHELL_HOME

Useful commands:
  tail -f $NUTSHELL_HOME/updater.log         # updater activity
  tail -f $NUTSHELL_HOME/server.log          # server stdout/stderr
  bash scripts/install-updater.sh --reinstall    # change launch args
  bash scripts/uninstall-updater.sh              # remove everything

EOF
